[workspace]
resolver = "2"
members = [
    "common",
    "datafile",
    "demo",
    "downloader",
    "event-loop",
    "gamenet/common",
    "gamenet/ddnet",
    "gamenet/spec",
    "gamenet/teeworlds-0.5",
    "gamenet/teeworlds-0.6",
    "gamenet/teeworlds-0.7",
    "huffman",
    "huffman/reference",
    "huffman/reference/sys",
    "logger",
    "map",
    "net",
    "packer",
    "render-map",
    "server",
    "serverbrowse",
    "snapshot",
    "socket",
    "stats-browser",
    "teehistorian",
    "tools",
    "wireshark-dissector",
    "world",
    "zlib-minimal",
]
