[package]
name = "libtw2-gamenet-teeworlds-0-6"
version = "0.0.1"
authors = ["heinrich5991 <heinrich5991@gmail.com>"]
license = "MIT/Apache-2.0"
edition = "2021"
rust-version = "1.63.0"

[dependencies]
arrayvec = "0.5.2"
buffer = "0.1.9"
libtw2-common = { path = "../../common/" }
libtw2-gamenet-common = { path = "../common/" }
libtw2-gamenet-snap = { path = "../snap/" }
libtw2-packer = { path = "../../packer/", features = ["uuid"] }
uuid = ">=0.8.1,<2.0.0"
warn = ">=0.1.1,<0.3.0"
