[package]
name = "libtw2-gamenet-snap"
version = "0.0.1"
authors = ["heinrich5991 <heinrich5991@gmail.com>"]
license = "MIT/Apache-2.0"
edition = "2021"

[dependencies]
buffer = "0.1.9"
libtw2-common = { path = "../../common" }
libtw2-gamenet-common = { path = "../common" }
libtw2-packer = { path = "../../packer/", features = ["uuid"] }
warn = ">=0.1.1,<0.3.0"
