[package]
authors = ["heinrich5991 <heinrich5991@gmail.com>"]
name = "teehistorian"
version = "0.0.1"
license = "MIT/Apache-2.0"

[dependencies]
arrayvec = { version = "0.5.2", features = ["serde"] }
buffer = "0.1.9"
common = { path = "../common/", features = ["serde"] }
chrono = "0.4.0"
itertools = "0.7.4"
serde = "1.0.23"
serde_derive = "1.0.7"
serde_json = "1.0.7"
packer = { path = "../packer/", features = ["uuid"] }
uuid = { version = "0.8.1", features = ["serde"] }
vec_map = "0.8.0"
warn = "0.2.2"

[dev-dependencies]
uuid = { version = "0.8.1", features = ["v3"] }
