[package]
name = "libtw2-snapshot"
version = "0.0.1"
authors = ["heinrich5991 <heinrich5991@gmail.com>"]
license = "MIT/Apache-2.0"
edition = "2021"

[dependencies]
buffer = "0.1.9"
libtw2-common = { path = "../common/" }
libtw2-gamenet-snap = { path = "../gamenet/snap/" }
libtw2-packer = { path = "../packer/" }
vec_map = "0.8.0"
warn = ">=0.1.1,<0.3.0"

[dev-dependencies]
libtw2-gamenet = { package = "libtw2-gamenet-teeworlds-0-6", path = "../gamenet/teeworlds-0.6/" }
