[package]
name = "gamenet_common"
version = "0.0.1"
authors = ["heinrich5991 <heinrich5991@gmail.com>"]
license = "MIT/Apache-2.0"

[dependencies]
arrayvec = "0.3.12"
buffer = "0.1.5"
common = { path = "../../common" }
packer = { path = "../../packer/", features = ["uuid"] }
serde = "1.0.23"
serde_derive = "1.0.7"
uuid = "0.8.1"
warn = ">=0.1.1,<0.3.0"
