[package]
name = "libtw2-gamenet-spec"
version = "0.0.1"
authors = ["heinrich5991 <heinrich5991@gmail.com>"]
license = "MIT/Apache-2.0"
edition = "2021"
rust-version = "1.63.0"

[dependencies]
libtw2-gamenet-common = { path = "../common/" }
serde = "1.0.23"
serde_derive = "1.0.7"
uuid = { version = ">=0.8.1,<2.0.0", features = ["serde"] }
