[package]
name = "packer"
version = "0.0.1"
authors = ["heinrich5991 <heinrich5991@gmail.com>"]
license = "MIT/Apache-2.0"

[dependencies]
arrayvec = "0.3.12"
buffer = "0.1.5"
common = { path = "../common/" }
uuid = { version = "0.5.1", optional = true }
warn = ">=0.1.1,<0.3.0"

[dev-dependencies]
hexdump = "0.1.0"
quickcheck = "0.4.1"
