[package]
name = "net"
version = "0.0.1"
authors = ["heinrich5991 <heinrich5991@gmail.com>"]
license = "MIT/Apache-2.0"

[dependencies]
arrayvec = "0.5.2"
assert_matches = "1.0.1"
buffer = "0.1.9"
common = { path = "../common/" }
huffman = { path = "../huffman/" }
linear-map = "1.0.0"
matches = "0.1.2"
optional = "0.0.12"
void = ">=0.0.4,<2.0.0"
warn = ">=0.1.1,<0.3.0"

[dev-dependencies]
hexdump = "0.1.1"
itertools = ">=0.3.0,<0.5.0"
quickcheck = "0.4.1"
